create table branches (
    id bigint generated by default as identity primary key,
    branch_code varchar(8) not null,
    branch_name varchar(100) not null,
    state varchar(2) not null,
    zip_code varchar(5) not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_branches_branch_code unique (branch_code)
);

create table products (
    id bigint generated by default as identity primary key,
    product_code varchar(8) not null,
    product_name varchar(100) not null,
    account_type varchar(20) not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_products_product_code unique (product_code),
    constraint chk_products_account_type check (account_type in ('DEPOSIT', 'CREDIT'))
);

create table pricing_plans (
    id bigint generated by default as identity primary key,
    plan_code varchar(8) not null,
    plan_name varchar(100) not null,
    product_code varchar(8) not null,
    product_name varchar(100) not null,
    region_code varchar(8) not null,
    region_name varchar(100) not null,
    active_from timestamp with time zone not null,
    active_to timestamp with time zone not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_pricing_plans_plan_code unique (plan_code)
);

create table regions (
    id bigint generated by default as identity primary key,
    region_code varchar(8) not null,
    region_name varchar(100) not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_regions_region_code unique (region_code)
);

create table region_branches (
    region_id bigint not null,
    branch_code varchar(8) not null,
    primary key (branch_code, region_id),
    constraint fk_region_branches_region_id foreign key (region_id) references regions (id)
);

create table region_states (
    region_id bigint not null,
    state_code varchar(2) not null,
    primary key (state_code, region_id),
    constraint fk_region_states_region_id foreign key (region_id) references regions (id)
);

create table region_zip_codes (
    region_id bigint not null,
    zip_code varchar(5) not null,
    primary key (zip_code, region_id),
    constraint fk_region_zip_codes_region_id foreign key (region_id) references regions (id)
);
