alter table eligibility_reason_conditions
    drop constraint fk_eligibility_reason_conditions_reason_id;

alter table eligibility_reason_conditions
    drop constraint fk_eligibility_reason_conditions_attribute_id;

alter table eligibility_reason_conditions
    drop constraint chk_eligibility_reason_conditions_operator;

create table eligibility_reason_conditions_with_id (
    id bigint generated by default as identity,
    reason_id bigint not null,
    attribute_id bigint not null,
    operator varchar(2) not null,
    attribute_value text not null,
    constraint pk_eligibility_reason_conditions primary key (id),
    constraint fk_eligibility_reason_conditions_reason_id
        foreign key (reason_id) references eligibility_reasons (id),
    constraint fk_eligibility_reason_conditions_attribute_id
        foreign key (attribute_id) references account_attributes (id),
    constraint chk_eligibility_reason_conditions_operator
        check (operator in ('=', '>', '<', '>=', '<=', '<>'))
);

insert into eligibility_reason_conditions_with_id (reason_id, attribute_id, operator, attribute_value)
select reason_id, attribute_id, operator, attribute_value
from eligibility_reason_conditions;

drop table eligibility_reason_conditions;

alter table eligibility_reason_conditions_with_id
    rename to eligibility_reason_conditions;
