create table region_branches_new (
    region_id bigint not null,
    branch_id bigint not null,
    primary key (branch_id, region_id),
    constraint fk_region_branches_new_region_id foreign key (region_id) references regions (id),
    constraint fk_region_branches_new_branch_id foreign key (branch_id) references branches (id),
    constraint uk_region_branches_new_branch_id unique (branch_id)
);

insert into region_branches_new (region_id, branch_id)
select rb.region_id, b.id
from region_branches rb
join branches b on b.branch_code = rb.branch_code;

drop table region_branches;

alter table region_branches_new rename to region_branches;

create table pricing_plans_new (
    id bigint generated by default as identity primary key,
    plan_code varchar(8) not null,
    plan_name varchar(100) not null,
    product_id bigint not null,
    region_id bigint not null,
    active_from timestamp with time zone not null,
    active_to timestamp with time zone not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_pricing_plans_new_plan_code unique (plan_code),
    constraint fk_pricing_plans_new_product_id foreign key (product_id) references products (id),
    constraint fk_pricing_plans_new_region_id foreign key (region_id) references regions (id)
);

insert into pricing_plans_new (id, plan_code, plan_name, product_id, region_id, active_from, active_to, updated_on, updated_by)
select pp.id, pp.plan_code, pp.plan_name, p.id, r.id, pp.active_from, pp.active_to, pp.updated_on, pp.updated_by
from pricing_plans pp
join products p on p.product_code = pp.product_code
join regions r on r.region_code = pp.region_code;

drop table pricing_plans;

alter table pricing_plans_new rename to pricing_plans;
