drop table pricing_plans;

create table pricing_plans (
    id bigint generated by default as identity primary key,
    plan_code varchar(8) not null,
    plan_name varchar(100) not null,
    product_id bigint not null,
    region_id bigint not null,
    active_from date not null,
    active_through date not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_pricing_plans_plan_code unique (plan_code),
    constraint fk_pricing_plans_product_id foreign key (product_id) references products (id),
    constraint fk_pricing_plans_region_id foreign key (region_id) references regions (id)
);
