create table account_attributes (
    id bigint generated by default as identity primary key,
    attribute_code varchar(8) not null,
    attribute_name varchar(100) not null,
    attribute_type varchar(20) not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_account_attributes_attribute_code unique (attribute_code),
    constraint chk_account_attributes_attribute_type check (attribute_type in ('TEXT', 'DECIMAL', 'INTEGER', 'DATE', 'BOOLEAN'))
);
