create table eligibility_reasons (
    id bigint generated by default as identity primary key,
    reason_code varchar(8) not null,
    reason_name varchar(100) not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_eligibility_reasons_reason_code unique (reason_code)
);

create table eligibility_reason_conditions (
    reason_id bigint not null,
    attribute_id bigint not null,
    operator varchar(2) not null,
    attribute_value text not null,
    primary key (reason_id, attribute_id, operator),
    constraint fk_eligibility_reason_conditions_reason_id
        foreign key (reason_id) references eligibility_reasons (id),
    constraint fk_eligibility_reason_conditions_attribute_id
        foreign key (attribute_id) references account_attributes (id),
    constraint chk_eligibility_reason_conditions_operator
        check (operator in ('=', '>', '<', '>=', '<=', '<>'))
);
