create table fees (
    id bigint generated by default as identity primary key,
    fee_code varchar(8) not null,
    fee_name varchar(100) not null,
    product_type varchar(20) not null,
    updated_on timestamp with time zone not null,
    updated_by varchar(100) not null,
    constraint uk_fees_fee_code unique (fee_code),
    constraint chk_fees_product_type check (product_type in ('DEPOSIT', 'CREDIT'))
);
